# Created By Teodor Rosolowski 09.2021 trteodor@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE BUILD_SYSTEM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

ifeq ($(MAKECMDGOALS),$(filter $(MAKECMDGOALS),))
helptest: help
endif
E :=
S := $E   $E
help:
	@echo     Call: make help \ \ \ -show this information
	@echo	  How Use it:
	@echo	  1. call: make all  \ \ \ -To compile output files for Microcontroller
	@echo	  Its default target generated by CubeMX so was Decided to dont modify it
		@echo	  ------------------------------------
	@echo	  2. Call: make test-ra \ \ \ \ \ \ -To start compilation or fully recompilation all unit-test
	@echo	  3. Call: make test-s \ \ \  \ \ \ -Only to rebuild source files and start unit tests
	@echo	  4. Call: make coverage \ \ \ \ \ -To refresh coverage report
	@echo	  ------------------------------------
	@echo	  5. call: make clean-test \ \ \ -To delete all test result
	@echo	  6. call: make clean-docs  \ \ \ -Remove Docs Folder '('currently contain only unit-tests coverage report')'
	@echo	  6. call: make clean  \ \ \ \ \ \ \ \ -Remove build Folder '('Carefully')'

ifeq ($(MAKECMDGOALS),$(filter $(MAKECMDGOALS),test test-ra test-s coverage clean-test clean-docs))
include test-main.mk
else
#Call Makefile which is generated by CubeMX - (normal compilation generated by CubeMX)
# "Call make all" to compile program for microcontroller
include Makefile
endif
