/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_SampleFileToUT.h"

static const char* CMockString_Data = "Data";
static const char* CMockString_DataRead = "DataRead";
static const char* CMockString_FakeI2cInit = "FakeI2cInit";
static const char* CMockString_FakeUartPrintInfo = "FakeUartPrintInfo";
static const char* CMockString_I2cHandler = "I2cHandler";
static const char* CMockString_ReadI2cSlaveDataRegister = "ReadI2cSlaveDataRegister";
static const char* CMockString_ReadingDataEndCB = "ReadingDataEndCB";
static const char* CMockString_RegNum = "RegNum";
static const char* CMockString_a = "a";
static const char* CMockString_c = "c";
static const char* CMockString_len = "len";
static const char* CMockString_validateData = "validateData";

typedef struct _CMOCK_FakeUartPrintInfo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_a;
  char* Expected_c;
  char ReturnThruPtr_c_Used;
  char* ReturnThruPtr_c_Val;
  size_t ReturnThruPtr_c_Size;

} CMOCK_FakeUartPrintInfo_CALL_INSTANCE;

typedef struct _CMOCK_FakeI2cInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  FakeStructHanldeI2c* Expected_I2cHandler;
  cmock_SampleFileToUT_func_ptr1 Expected_ReadingDataEndCB;
  char ReturnThruPtr_I2cHandler_Used;
  FakeStructHanldeI2c* ReturnThruPtr_I2cHandler_Val;
  size_t ReturnThruPtr_I2cHandler_Size;

} CMOCK_FakeI2cInit_CALL_INSTANCE;

typedef struct _CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  FakeStructHanldeI2c* Expected_I2cHandler;
  uint8_t* Expected_RegNum;
  uint8_t* Expected_DataRead;
  char ReturnThruPtr_I2cHandler_Used;
  FakeStructHanldeI2c* ReturnThruPtr_I2cHandler_Val;
  size_t ReturnThruPtr_I2cHandler_Size;
  char ReturnThruPtr_RegNum_Used;
  uint8_t* ReturnThruPtr_RegNum_Val;
  size_t ReturnThruPtr_RegNum_Size;
  char ReturnThruPtr_DataRead_Used;
  uint8_t* ReturnThruPtr_DataRead_Val;
  size_t ReturnThruPtr_DataRead_Size;

} CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE;

typedef struct _CMOCK_validateData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  FakeStructHanldeI2c* Expected_I2cHandler;
  uint8_t* Expected_Data;
  uint8_t Expected_len;
  char ReturnThruPtr_I2cHandler_Used;
  FakeStructHanldeI2c* ReturnThruPtr_I2cHandler_Val;
  size_t ReturnThruPtr_I2cHandler_Size;
  char ReturnThruPtr_Data_Used;
  uint8_t* ReturnThruPtr_Data_Val;
  size_t ReturnThruPtr_Data_Size;

} CMOCK_validateData_CALL_INSTANCE;

static struct mock_SampleFileToUTInstance
{
  char FakeUartPrintInfo_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE FakeUartPrintInfo_CallInstance;
  char FakeI2cInit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE FakeI2cInit_CallInstance;
  char ReadI2cSlaveDataRegister_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE ReadI2cSlaveDataRegister_CallInstance;
  char validateData_IgnoreBool;
  int validateData_FinalReturn;
  CMOCK_MEM_INDEX_TYPE validateData_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_SampleFileToUT_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.FakeUartPrintInfo_CallInstance;
  if (Mock.FakeUartPrintInfo_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FakeUartPrintInfo);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FakeI2cInit_CallInstance;
  if (Mock.FakeI2cInit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FakeI2cInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.ReadI2cSlaveDataRegister_CallInstance;
  if (Mock.ReadI2cSlaveDataRegister_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ReadI2cSlaveDataRegister);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.validateData_CallInstance;
  if (Mock.validateData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_validateData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_SampleFileToUT_Init(void)
{
  mock_SampleFileToUT_Destroy();
}

void mock_SampleFileToUT_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void FakeUartPrintInfo(uint8_t a, char* c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FakeUartPrintInfo_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FakeUartPrintInfo);
  cmock_call_instance = (CMOCK_FakeUartPrintInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FakeUartPrintInfo_CallInstance);
  Mock.FakeUartPrintInfo_CallInstance = CMock_Guts_MemNext(Mock.FakeUartPrintInfo_CallInstance);
  if (Mock.FakeUartPrintInfo_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FakeUartPrintInfo,CMockString_a);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_a, a, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FakeUartPrintInfo,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_FakeUartPrintInfo(CMOCK_FakeUartPrintInfo_CALL_INSTANCE* cmock_call_instance, uint8_t a, char* c);
void CMockExpectParameters_FakeUartPrintInfo(CMOCK_FakeUartPrintInfo_CALL_INSTANCE* cmock_call_instance, uint8_t a, char* c)
{
  cmock_call_instance->Expected_a = a;
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
}

void FakeUartPrintInfo_CMockIgnore(void)
{
  Mock.FakeUartPrintInfo_IgnoreBool = (char)1;
}

void FakeUartPrintInfo_CMockStopIgnore(void)
{
  Mock.FakeUartPrintInfo_IgnoreBool = (char)0;
}

void FakeUartPrintInfo_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t a, char* c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FakeUartPrintInfo_CALL_INSTANCE));
  CMOCK_FakeUartPrintInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_FakeUartPrintInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FakeUartPrintInfo_CallInstance = CMock_Guts_MemChain(Mock.FakeUartPrintInfo_CallInstance, cmock_guts_index);
  Mock.FakeUartPrintInfo_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FakeUartPrintInfo(cmock_call_instance, a, c);
}

void FakeUartPrintInfo_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, char* c, size_t cmock_size)
{
  CMOCK_FakeUartPrintInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_FakeUartPrintInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FakeUartPrintInfo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void FakeI2cInit(FakeStructHanldeI2c* I2cHandler, cmock_SampleFileToUT_func_ptr1 ReadingDataEndCB)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FakeI2cInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FakeI2cInit);
  cmock_call_instance = (CMOCK_FakeI2cInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FakeI2cInit_CallInstance);
  Mock.FakeI2cInit_CallInstance = CMock_Guts_MemNext(Mock.FakeI2cInit_CallInstance);
  if (Mock.FakeI2cInit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FakeI2cInit,CMockString_I2cHandler);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_I2cHandler), (void*)(I2cHandler), sizeof(FakeStructHanldeI2c), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FakeI2cInit,CMockString_ReadingDataEndCB);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ReadingDataEndCB, ReadingDataEndCB, cmock_line, CMockStringMismatch);
  }
  if (cmock_call_instance->ReturnThruPtr_I2cHandler_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(I2cHandler, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)I2cHandler, (void*)cmock_call_instance->ReturnThruPtr_I2cHandler_Val,
      cmock_call_instance->ReturnThruPtr_I2cHandler_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_FakeI2cInit(CMOCK_FakeI2cInit_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, cmock_SampleFileToUT_func_ptr1 ReadingDataEndCB);
void CMockExpectParameters_FakeI2cInit(CMOCK_FakeI2cInit_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, cmock_SampleFileToUT_func_ptr1 ReadingDataEndCB)
{
  cmock_call_instance->Expected_I2cHandler = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_ReadingDataEndCB), (void*)(&ReadingDataEndCB),
         sizeof(cmock_SampleFileToUT_func_ptr1[sizeof(ReadingDataEndCB) == sizeof(cmock_SampleFileToUT_func_ptr1) ? 1 : -1])); /* add cmock_SampleFileToUT_func_ptr1 to :treat_as_array if this causes an error */
}

void FakeI2cInit_CMockIgnore(void)
{
  Mock.FakeI2cInit_IgnoreBool = (char)1;
}

void FakeI2cInit_CMockStopIgnore(void)
{
  Mock.FakeI2cInit_IgnoreBool = (char)0;
}

void FakeI2cInit_CMockExpect(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, cmock_SampleFileToUT_func_ptr1 ReadingDataEndCB)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FakeI2cInit_CALL_INSTANCE));
  CMOCK_FakeI2cInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_FakeI2cInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FakeI2cInit_CallInstance = CMock_Guts_MemChain(Mock.FakeI2cInit_CallInstance, cmock_guts_index);
  Mock.FakeI2cInit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FakeI2cInit(cmock_call_instance, I2cHandler, ReadingDataEndCB);
}

void FakeI2cInit_CMockReturnMemThruPtr_I2cHandler(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, size_t cmock_size)
{
  CMOCK_FakeI2cInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_FakeI2cInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FakeI2cInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 1;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Val = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Size = cmock_size;
}

void ReadI2cSlaveDataRegister(FakeStructHanldeI2c* I2cHandler, uint8_t* RegNum, uint8_t* DataRead)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ReadI2cSlaveDataRegister);
  cmock_call_instance = (CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ReadI2cSlaveDataRegister_CallInstance);
  Mock.ReadI2cSlaveDataRegister_CallInstance = CMock_Guts_MemNext(Mock.ReadI2cSlaveDataRegister_CallInstance);
  if (Mock.ReadI2cSlaveDataRegister_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_ReadI2cSlaveDataRegister,CMockString_I2cHandler);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_I2cHandler), (void*)(I2cHandler), sizeof(FakeStructHanldeI2c), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_ReadI2cSlaveDataRegister,CMockString_RegNum);
    if (cmock_call_instance->Expected_RegNum == NULL)
      { UNITY_TEST_ASSERT_NULL(RegNum, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_RegNum, RegNum, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_ReadI2cSlaveDataRegister,CMockString_DataRead);
    if (cmock_call_instance->Expected_DataRead == NULL)
      { UNITY_TEST_ASSERT_NULL(DataRead, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_DataRead, DataRead, 1, cmock_line, CMockStringMismatch); }
  }
  if (cmock_call_instance->ReturnThruPtr_I2cHandler_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(I2cHandler, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)I2cHandler, (void*)cmock_call_instance->ReturnThruPtr_I2cHandler_Val,
      cmock_call_instance->ReturnThruPtr_I2cHandler_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_RegNum_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(RegNum, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)RegNum, (void*)cmock_call_instance->ReturnThruPtr_RegNum_Val,
      cmock_call_instance->ReturnThruPtr_RegNum_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_DataRead_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(DataRead, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)DataRead, (void*)cmock_call_instance->ReturnThruPtr_DataRead_Val,
      cmock_call_instance->ReturnThruPtr_DataRead_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_ReadI2cSlaveDataRegister(CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, uint8_t* RegNum, uint8_t* DataRead);
void CMockExpectParameters_ReadI2cSlaveDataRegister(CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, uint8_t* RegNum, uint8_t* DataRead)
{
  cmock_call_instance->Expected_I2cHandler = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 0;
  cmock_call_instance->Expected_RegNum = RegNum;
  cmock_call_instance->ReturnThruPtr_RegNum_Used = 0;
  cmock_call_instance->Expected_DataRead = DataRead;
  cmock_call_instance->ReturnThruPtr_DataRead_Used = 0;
}

void ReadI2cSlaveDataRegister_CMockIgnore(void)
{
  Mock.ReadI2cSlaveDataRegister_IgnoreBool = (char)1;
}

void ReadI2cSlaveDataRegister_CMockStopIgnore(void)
{
  Mock.ReadI2cSlaveDataRegister_IgnoreBool = (char)0;
}

void ReadI2cSlaveDataRegister_CMockExpect(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, uint8_t* RegNum, uint8_t* DataRead)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE));
  CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ReadI2cSlaveDataRegister_CallInstance = CMock_Guts_MemChain(Mock.ReadI2cSlaveDataRegister_CallInstance, cmock_guts_index);
  Mock.ReadI2cSlaveDataRegister_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ReadI2cSlaveDataRegister(cmock_call_instance, I2cHandler, RegNum, DataRead);
}

void ReadI2cSlaveDataRegister_CMockReturnMemThruPtr_I2cHandler(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, size_t cmock_size)
{
  CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ReadI2cSlaveDataRegister_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 1;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Val = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Size = cmock_size;
}

void ReadI2cSlaveDataRegister_CMockReturnMemThruPtr_RegNum(UNITY_LINE_TYPE cmock_line, uint8_t* RegNum, size_t cmock_size)
{
  CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ReadI2cSlaveDataRegister_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_RegNum_Used = 1;
  cmock_call_instance->ReturnThruPtr_RegNum_Val = RegNum;
  cmock_call_instance->ReturnThruPtr_RegNum_Size = cmock_size;
}

void ReadI2cSlaveDataRegister_CMockReturnMemThruPtr_DataRead(UNITY_LINE_TYPE cmock_line, uint8_t* DataRead, size_t cmock_size)
{
  CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_ReadI2cSlaveDataRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ReadI2cSlaveDataRegister_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_DataRead_Used = 1;
  cmock_call_instance->ReturnThruPtr_DataRead_Val = DataRead;
  cmock_call_instance->ReturnThruPtr_DataRead_Size = cmock_size;
}

int validateData(FakeStructHanldeI2c* I2cHandler, uint8_t* Data, uint8_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_validateData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_validateData);
  cmock_call_instance = (CMOCK_validateData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.validateData_CallInstance);
  Mock.validateData_CallInstance = CMock_Guts_MemNext(Mock.validateData_CallInstance);
  if (Mock.validateData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.validateData_FinalReturn;
    Mock.validateData_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_validateData,CMockString_I2cHandler);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_I2cHandler), (void*)(I2cHandler), sizeof(FakeStructHanldeI2c), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_validateData,CMockString_Data);
    if (cmock_call_instance->Expected_Data == NULL)
      { UNITY_TEST_ASSERT_NULL(Data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_Data, Data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_validateData,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  if (cmock_call_instance->ReturnThruPtr_I2cHandler_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(I2cHandler, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)I2cHandler, (void*)cmock_call_instance->ReturnThruPtr_I2cHandler_Val,
      cmock_call_instance->ReturnThruPtr_I2cHandler_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_Data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(Data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)Data, (void*)cmock_call_instance->ReturnThruPtr_Data_Val,
      cmock_call_instance->ReturnThruPtr_Data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_validateData(CMOCK_validateData_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, uint8_t* Data, uint8_t len);
void CMockExpectParameters_validateData(CMOCK_validateData_CALL_INSTANCE* cmock_call_instance, FakeStructHanldeI2c* I2cHandler, uint8_t* Data, uint8_t len)
{
  cmock_call_instance->Expected_I2cHandler = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 0;
  cmock_call_instance->Expected_Data = Data;
  cmock_call_instance->ReturnThruPtr_Data_Used = 0;
  cmock_call_instance->Expected_len = len;
}

void validateData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_validateData_CALL_INSTANCE));
  CMOCK_validateData_CALL_INSTANCE* cmock_call_instance = (CMOCK_validateData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.validateData_CallInstance = CMock_Guts_MemChain(Mock.validateData_CallInstance, cmock_guts_index);
  Mock.validateData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.validateData_IgnoreBool = (char)1;
}

void validateData_CMockStopIgnore(void)
{
  if(Mock.validateData_IgnoreBool)
    Mock.validateData_CallInstance = CMock_Guts_MemNext(Mock.validateData_CallInstance);
  Mock.validateData_IgnoreBool = (char)0;
}

void validateData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, uint8_t* Data, uint8_t len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_validateData_CALL_INSTANCE));
  CMOCK_validateData_CALL_INSTANCE* cmock_call_instance = (CMOCK_validateData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.validateData_CallInstance = CMock_Guts_MemChain(Mock.validateData_CallInstance, cmock_guts_index);
  Mock.validateData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_validateData(cmock_call_instance, I2cHandler, Data, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void validateData_CMockReturnMemThruPtr_I2cHandler(UNITY_LINE_TYPE cmock_line, FakeStructHanldeI2c* I2cHandler, size_t cmock_size)
{
  CMOCK_validateData_CALL_INSTANCE* cmock_call_instance = (CMOCK_validateData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.validateData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_I2cHandler_Used = 1;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Val = I2cHandler;
  cmock_call_instance->ReturnThruPtr_I2cHandler_Size = cmock_size;
}

void validateData_CMockReturnMemThruPtr_Data(UNITY_LINE_TYPE cmock_line, uint8_t* Data, size_t cmock_size)
{
  CMOCK_validateData_CALL_INSTANCE* cmock_call_instance = (CMOCK_validateData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.validateData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_Data_Used = 1;
  cmock_call_instance->ReturnThruPtr_Data_Val = Data;
  cmock_call_instance->ReturnThruPtr_Data_Size = cmock_size;
}

